language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
  - "6"
  - "4"
  - "iojs"
  - "0.12"
  - "0.10"
  - "0.8"
sudo: false
before_install:
  - 'nvm install-latest-npm'
matrix:
  fast_finish: true
